name: RSS to Telegram channel ⭐️

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt

      - name: Download NLTK punkt
        run: python -c "import nltk; nltk.download('punkt')"

      - name: Run RSS -> Telegram script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FEEDS_CSV_URL: ${{ secrets.FEEDS_CSV_URL }}
          FUZZY_THRESHOLD: ${{ secrets.FUZZY_THRESHOLD }}
        run: |
          python rss_to_telegram.py --feeds-csv "$FEEDS_CSV_URL" \
                                     --posted-file "posted.json" \
                                     --fuzzy-threshold "${FUZZY_THRESHOLD:-88}"

      - name: Commit posted.json
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions[bot]"
          git add posted.json || true
          if ! git diff --staged --quiet; then
            git commit -m "Update posted.json" || true
            git push
